### ISSUE TITLE
i have build in windows,and open in visual studio 2022,which one is the start program? i have tried each of them,but i haven`t seen the image.

### ISSUE THREAD

**Issue by jlk1997** [mandyedi/raytracing-from-the-ground-up#26]
how can i  see the render image in visualstudio ? thx
![image](https://user-images.githubusercontent.com/56379549/222943778-8be64b15-6bd4-4e7f-8eb0-54a7f19b9802.png)

**Comment by mandyedi** [comment]
Hi @jlk1997 
Set the consoleApp as the startup project then run it. The rendered image should be in the build folder (this folder is not added to the Visual Studio solution).
If you still have trouble with it, let me know. I'll have access to a PC with Windows in a few days and I can check it.
